################################# Default configuration ###################
baseURL = "https://opentenbase.org"
title = "OpenTenBase"
theme = "meghna-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Asia/Shanghai"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 45 # see https://gohugo.io/content-management/excerpts/
# defaultContentLanguage
defaultContentLanguage = "cn"
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = true #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"



################### Chinese Navigation ########################
[[Languages.cn.menu.main]]
name = "新闻"
url = "#news"
weight = 1

[[Languages.cn.menu.main]]
name = "文章"
url = "#blog"
weight = 2

[[Languages.cn.menu.main]]
name = "活动"
url = "#event"
weight = 3

[[Languages.cn.menu.main]]
name = "文档"
url = "https://docs.opentenbase.org/"
weight = 4

[[Languages.cn.menu.main]]
name = "认证"
url = "event/certification"
weight = 5

[[Languages.cn.menu.main]]
name = "下载"
url = "https://github.com/OpenTenBase/OpenTenBase/tags"
weight = 6

[[Languages.cn.menu.main]]
name = "源码"
url = "https://github.com/OpenTenBase/OpenTenBase"
weight = 7

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "News"
url = "#news"
weight = 1

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 2

[[Languages.en.menu.main]]
name = "Event"
url = "#event"
weight = 3

[[Languages.en.menu.main]]
name = "Document"
url = "https://docs.opentenbase.org/en/"
weight = 4

[[Languages.en.menu.main]]
name = "Download"
url = "https://github.com/OpenTenBase/OpenTenBase/tags"
weight = 5

[[Languages.en.menu.main]]
name = "Code"
url = "https://github.com/OpenTenBase/OpenTenBase"
weight = 6


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
logo_footer = "images/logo_footer.png"
qr_code = "images/qr.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo_footer.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ Chinese Language ########################
[Languages.cn]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/chinese"
#weight = 1

[Languages.cn.params]
home = "首页"
copyright = "Copyright © 2013 - 2025 Tencent Cloud. All Rights Reserved. 腾讯云 版权所有"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"

[Languages.en.params]
weight = 2
home = "Home"
copyright = "Copyright © 2013 - 2025 Tencent Cloud. All Rights Reserved. 腾讯云 版权所有"
